#!/usr/bin/env python3
"""Generate a time-bounded exact dependency lock for one vLLM task."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import tempfile
from pathlib import Path

import tomllib

REPO_ROOT = Path(__file__).resolve().parents[2]
VLLM_REPO = "https://github.com/vllm-project/vllm.git"
UV_VERSION = "0.11.28"
EXTRA_INDEX_LINE = "--extra-index-url https://download.pytorch.org/whl/cpu"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(args: list[str], *, cwd: Path) -> None:
    subprocess.run(args, cwd=cwd, check=True)


def generate(task_dir: Path) -> None:
    task_dir = task_dir.resolve()
    config = tomllib.loads((task_dir / "task.toml").read_text())
    base_commit = config["metadata"]["base_commit"]
    cutoff = config["metadata"]["dependency_cutoff"]
    cutoff_overrides = config["metadata"].get("dependency_cutoff_overrides", [])
    lock_dir = task_dir / "environment" / "lock"
    extras = lock_dir / "extras.in"
    if not extras.is_file():
        raise FileNotFoundError(f"missing task lock extras: {extras}")

    with tempfile.TemporaryDirectory(prefix="vllm-lock-source-") as raw_tmp:
        source = Path(raw_tmp)
        run(
            ["git", "clone", "--filter=blob:none", "--no-checkout", VLLM_REPO, "."],
            cwd=source,
        )
        run(["git", "checkout", "--detach", base_commit], cwd=source)

        build_candidates = [
            Path("requirements/build/cpu.txt"),
            Path("requirements/cpu-build.txt"),
        ]
        build_requirements = next(
            (path for path in build_candidates if (source / path).is_file()), None
        )
        if build_requirements is None:
            raise FileNotFoundError("no CPU build requirements found in pinned source")
        relative_inputs = [
            Path("requirements/cpu.txt"),
            Path("requirements/common.txt"),
            build_requirements,
        ]
        source_hashes = {str(path): sha256(source / path) for path in relative_inputs}

        normalized_hashes: dict[str, str] = {}
        for relative in (Path("requirements/cpu.txt"), build_requirements):
            path = source / relative
            lines = path.read_text().splitlines()
            lines = [line for line in lines if line != EXTRA_INDEX_LINE]
            path.write_text("\n".join(lines) + "\n")
            normalized_hashes[str(relative)] = sha256(path)
        normalized_hashes["requirements/common.txt"] = source_hashes[
            "requirements/common.txt"
        ]

        output = lock_dir / "requirements.txt"
        command = [
            "uvx",
            "--from",
            f"uv=={UV_VERSION}",
            "uv",
            "pip",
            "compile",
            "requirements/cpu.txt",
            str(build_requirements),
            str(extras),
            "--python-version",
            "3.12",
            "--python-platform",
            "x86_64-manylinux_2_28",
            "--exclude-newer",
            cutoff,
            "--torch-backend",
            "cpu",
            "--index-strategy",
            "first-index",
            "--output-file",
            str(output),
        ]
        for override in cutoff_overrides:
            command.extend(["--exclude-newer-package", override])
        run(command, cwd=source)

    lines = output.read_text().splitlines()
    if lines and lines[0].startswith("# This file was autogenerated by uv"):
        lines = lines[2:]
    lines = [line.replace(str(extras), "extras.in") for line in lines]
    header = [
        f"# Generated with uv {UV_VERSION} from the pinned base requirements and task",
        "# extras for CPython 3.12 on x86_64 manylinux_2_28. Packages newer than",
        f"# {cutoff} were excluded during resolution.",
    ]
    output.write_text("\n".join(header + lines) + "\n")

    package_count = sum(
        bool(re.match(r"^[A-Za-z0-9][A-Za-z0-9._-]*==", line))
        for line in output.read_text().splitlines()
    )
    manifest = {
        "schema_version": "vllm_dependency_lock.v1",
        "resolver": f"uv {UV_VERSION}",
        "base_commit": base_commit,
        "dependency_cutoff": cutoff,
        "dependency_cutoff_overrides": cutoff_overrides,
        "python_version": "3.12",
        "python_platform": "x86_64-manylinux_2_28",
        "torch_backend": "cpu",
        "index_strategy": "first-index",
        "inputs": {
            path: {
                "source_sha256": source_hashes[path],
                "resolver_input_sha256": normalized_hashes[path],
            }
            for path in source_hashes
        }
        | {"extras.in": {"sha256": sha256(extras)}},
        "normalization": {
            "removed_line": EXTRA_INDEX_LINE,
            "reason": (
                "uv --torch-backend cpu scopes the PyTorch index to torch packages; "
                "removing the generic extra index prevents unrelated packages without "
                "upload timestamps from bypassing the cutoff"
            ),
        },
        "command": (
            f"uv pip compile requirements/cpu.txt {build_requirements} extras.in "
            f"--python-version 3.12 --python-platform x86_64-manylinux_2_28 "
            f"--exclude-newer {cutoff} --torch-backend cpu "
            "--index-strategy first-index --output-file requirements.txt"
            + "".join(
                f" --exclude-newer-package {override}" for override in cutoff_overrides
            )
        ),
        "output": {
            "path": "environment/lock/requirements.txt",
            "packages": package_count,
            "sha256": sha256(output),
        },
    }
    (lock_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n"
    )
    print(f"LOCKED {package_count} packages {output}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("task_dirs", nargs="+", type=Path)
    args = parser.parse_args()
    for raw in args.task_dirs:
        task_dir = raw if raw.is_absolute() else REPO_ROOT / raw
        generate(task_dir)


if __name__ == "__main__":
    main()
