#!/usr/bin/env python3
"""Write tests/base-manifest.json: SHA-256 of every Base file a pi task verifier protects.

The verifier (tests/check_scope.py) must decide whether a submission changed pi core, the
build/test toolchain, or an existing test file. It cannot ask git: the checkout and its
.git belong to the agent, and `git update-index --assume-unchanged`, a `.gitignore` line
or `.git/info/exclude` hide changes from `git status`. The manifest is derived from the
pinned Base commit, is identical on every platform and image build, and ships in tests/,
which the agent never sees.

Usage (repository root; reads the files out of a built task image):
    python3 templates/pi-harbor-node/base_manifest.py <image> tasks/<task> [tasks/<task> ...]
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

# Paths a submission may not change or add to (pi source, the build/test toolchain it is
# about to be run with), relative to the pi checkout. Same rule the verifier has always
# applied; only the detection moved from `git status` to content hashes.
SCOPE_PATTERN = (
    r"^(packages/[^/]+/src/|scripts/|\.github/|\.npmrc$|package\.json$|package-lock\.json$"
    r"|tsconfig[^/]*\.json$|biome\.json$|vitest[^/]*$|vite\.config[^/]*$"
    r"|packages/[^/]+/(package\.json|tsconfig[^/]*\.json|vitest[^/]*|vite\.config[^/]*)$)"
)
# Existing test files must stay byte-identical; new files under it are allowed.
TESTS_PREFIX = "packages/coding-agent/test/"

SCRIPT = r"""
set -euo pipefail
cd /workspace/pi
test -z "$(git status --porcelain)"
git rev-parse HEAD
git ls-files -z | xargs -0 sha256sum
"""


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    image, task_dirs = sys.argv[1], [Path(p) for p in sys.argv[2:]]
    out = subprocess.run(
        ["docker", "run", "--rm", "-i", image, "bash", "-s"],
        input=SCRIPT, text=True, capture_output=True, check=True,
    ).stdout.splitlines()
    base_commit, lines = out[0].strip(), out[1:]
    scope = re.compile(SCOPE_PATTERN)
    files: dict[str, str] = {}
    for line in lines:
        digest, path = line.split("  ", 1)
        if scope.search(path) or path.startswith(TESTS_PREFIX):
            files[path] = digest
    manifest = {
        "schema_version": 1,
        "note": "SHA-256 of the Base files the verifier protects; generated by "
        "templates/pi-harbor-node/base_manifest.py from the pinned Base commit.",
        "base_commit": base_commit,
        "scope_pattern": SCOPE_PATTERN,
        "tests_prefix": TESTS_PREFIX,
        "files": dict(sorted(files.items())),
    }
    text = json.dumps(manifest, indent=1) + "\n"
    for task_dir in task_dirs:
        target = task_dir / "tests" / "base-manifest.json"
        target.write_text(text)
        print(f"WROTE {len(files)} files @ {base_commit[:12]} {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
