"""Verifier-owned case inventory; contains no candidate imports."""

ADDITIONAL_CASES = [{'id': 'after-quote-transcription-nonstream',
  'api': 'transcription',
  'stream': False,
  'language': 'en',
  'to_language': None,
  'chunks': [('He said "hello."',), ('Next sentence.',)],
  'expected': 'He said "hello." Next sentence.',
  'structured': False},
 {'id': 'after-quote-transcription-stream',
  'api': 'transcription',
  'stream': True,
  'language': 'en',
  'to_language': None,
  'chunks': [('He said "hello."',), ('Next sentence.',)],
  'expected': 'He said "hello." Next sentence.',
  'structured': False},
 {'id': 'after-quote-translation-nonstream',
  'api': 'translation',
  'stream': False,
  'language': 'en',
  'to_language': None,
  'chunks': [('He said "hello."',), ('Next sentence.',)],
  'expected': 'He said "hello." Next sentence.',
  'structured': False},
 {'id': 'after-quote-translation-stream',
  'api': 'translation',
  'stream': True,
  'language': 'en',
  'to_language': None,
  'chunks': [('He said "hello."',), ('Next sentence.',)],
  'expected': 'He said "hello." Next sentence.',
  'structured': False},
 {'id': 'before-quote-transcription-nonstream',
  'api': 'transcription',
  'stream': False,
  'language': 'en',
  'to_language': None,
  'chunks': [('He stopped.',), ('"Go," she said.',)],
  'expected': 'He stopped. "Go," she said.',
  'structured': False},
 {'id': 'before-quote-transcription-stream',
  'api': 'transcription',
  'stream': True,
  'language': 'en',
  'to_language': None,
  'chunks': [('He stopped.',), ('"Go," she said.',)],
  'expected': 'He stopped. "Go," she said.',
  'structured': False},
 {'id': 'before-quote-translation-nonstream',
  'api': 'translation',
  'stream': False,
  'language': 'en',
  'to_language': None,
  'chunks': [('He stopped.',), ('"Go," she said.',)],
  'expected': 'He stopped. "Go," she said.',
  'structured': False},
 {'id': 'before-quote-translation-stream',
  'api': 'translation',
  'stream': True,
  'language': 'en',
  'to_language': None,
  'chunks': [('He stopped.',), ('"Go," she said.',)],
  'expected': 'He stopped. "Go," she said.',
  'structured': False},
 {'id': 'inferred-chinese-nonstream',
  'api': 'transcription',
  'stream': False,
  'language': None,
  'to_language': None,
  'chunks': [('你好',), ('世界',)],
  'expected': '你好世界',
  'structured': False},
 {'id': 'inferred-chinese-stream',
  'api': 'transcription',
  'stream': True,
  'language': None,
  'to_language': None,
  'chunks': [('你好',), ('世界',)],
  'expected': '你好世界',
  'structured': False},
 {'id': 'inferred-japanese-nonstream',
  'api': 'transcription',
  'stream': False,
  'language': None,
  'to_language': None,
  'chunks': [('はじめまして',), ('よろしく',)],
  'expected': 'はじめましてよろしく',
  'structured': False},
 {'id': 'inferred-japanese-stream',
  'api': 'transcription',
  'stream': True,
  'language': None,
  'to_language': None,
  'chunks': [('はじめまして',), ('よろしく',)],
  'expected': 'はじめましてよろしく',
  'structured': False},
 {'id': 'inferred-chinese-quotes-nonstream',
  'api': 'transcription',
  'stream': False,
  'language': None,
  'to_language': None,
  'chunks': [('他说"你好。"',), ('"继续。"',)],
  'expected': '他说"你好。""继续。"',
  'structured': False},
 {'id': 'inferred-chinese-quotes-stream',
  'api': 'transcription',
  'stream': True,
  'language': None,
  'to_language': None,
  'chunks': [('他说"你好。"',), ('"继续。"',)],
  'expected': '他说"你好。""继续。"',
  'structured': False},
 {'id': 'inferred-halfwidth-katakana-nonstream',
  'api': 'transcription',
  'stream': False,
  'language': None,
  'to_language': None,
  'chunks': [('ｺﾝﾆﾁﾊ',), ('ｾｶｲ',)],
  'expected': 'ｺﾝﾆﾁﾊｾｶｲ',
  'structured': False},
 {'id': 'inferred-halfwidth-katakana-stream',
  'api': 'transcription',
  'stream': True,
  'language': None,
  'to_language': None,
  'chunks': [('ｺﾝﾆﾁﾊ',), ('ｾｶｲ',)],
  'expected': 'ｺﾝﾆﾁﾊｾｶｲ',
  'structured': False},
 {'id': 'inferred-chinese-empty-middle-nonstream',
  'api': 'transcription',
  'stream': False,
  'language': None,
  'to_language': None,
  'chunks': [('你好',), ('',), ('世界',)],
  'expected': '你好世界',
  'structured': False},
 {'id': 'inferred-chinese-empty-middle-stream',
  'api': 'transcription',
  'stream': True,
  'language': None,
  'to_language': None,
  'chunks': [('你好',), ('',), ('世界',)],
  'expected': '你好世界',
  'structured': False},
 {'id': 'qwen-unset-en-transcription',
  'api': 'transcription',
  'stream': False,
  'language': None,
  'to_language': None,
  'chunks': [('language English<asr_text>First sentence.',),
             ('language English<asr_text>Second sentence.',)],
  'expected': 'First sentence. Second sentence.',
  'structured': True},
 {'id': 'qwen-unset-en-translation',
  'api': 'translation',
  'stream': False,
  'language': None,
  'to_language': None,
  'chunks': [('language English<asr_text>First sentence.',),
             ('language English<asr_text>Second sentence.',)],
  'expected': 'First sentence. Second sentence.',
  'structured': True},
 {'id': 'qwen-unset-zh-transcription',
  'api': 'transcription',
  'stream': False,
  'language': None,
  'to_language': None,
  'chunks': [('language Chinese<asr_text>你好',), ('language Chinese<asr_text>世界',)],
  'expected': '你好世界',
  'structured': True},
 {'id': 'qwen-unset-zh-translation',
  'api': 'translation',
  'stream': False,
  'language': None,
  'to_language': 'zh',
  'chunks': [('language Chinese<asr_text>你好',), ('language Chinese<asr_text>世界',)],
  'expected': '你好世界',
  'structured': True},
 {'id': 'qwen-unset-ja-transcription',
  'api': 'transcription',
  'stream': False,
  'language': None,
  'to_language': None,
  'chunks': [('language Japanese<asr_text>はじめまして',),
             ('language Japanese<asr_text>よろしく',)],
  'expected': 'はじめましてよろしく',
  'structured': True},
 {'id': 'qwen-unset-ja-translation',
  'api': 'translation',
  'stream': False,
  'language': None,
  'to_language': 'ja',
  'chunks': [('language Japanese<asr_text>はじめまして',),
             ('language Japanese<asr_text>よろしく',)],
  'expected': 'はじめましてよろしく',
  'structured': True}]

REGRESSION_CASES = set(['test_empty_model_delta_does_not_consume_chunk_boundary[nonstream]',
 'test_empty_model_delta_does_not_consume_chunk_boundary[stream]',
 'test_existing_leading_whitespace_is_not_duplicated[transcription-False]',
 'test_existing_leading_whitespace_is_not_duplicated[transcription-True]',
 'test_existing_leading_whitespace_is_not_duplicated[translation-False]',
 'test_existing_leading_whitespace_is_not_duplicated[translation-True]',
 'test_existing_trailing_whitespace_is_not_duplicated[nonstream]',
 'test_existing_trailing_whitespace_is_not_duplicated[stream]',
 'test_public_multichunk_speech_behavior[nonstream-transcription-chinese]',
 'test_public_multichunk_speech_behavior[nonstream-transcription-punctuation]',
 'test_public_multichunk_speech_behavior[nonstream-translation-default-english]',
 'test_public_multichunk_speech_behavior[nonstream-translation-japanese-target]',
 'test_public_multichunk_speech_behavior[nonstream-translation-punctuation]',
 'test_public_multichunk_speech_behavior[stream-transcription-example]',
 'test_public_multichunk_speech_behavior[stream-transcription-japanese]',
 'test_public_multichunk_speech_behavior[stream-transcription-language-unset]',
 'test_public_multichunk_speech_behavior[stream-translation-chinese-target]',
 'test_public_multichunk_speech_behavior[stream-translation-default-english]',
 'test_qwen3_nonstreaming_structured_chunks_preserve_word_boundaries[transcription]',
 'test_qwen3_nonstreaming_structured_chunks_preserve_word_boundaries[translation]',
 'test_single_audio_chunk_has_no_leading_separator[transcription]',
 'test_single_audio_chunk_has_no_leading_separator[translation]',
 'test_streaming_separator_is_added_once_per_audio_chunk[transcription]',
 'test_streaming_separator_is_added_once_per_audio_chunk[translation]'])
REGRESSION_CASES |= {
    "test_additional_chunk_boundaries[" + case["id"] + "]"
    for case in ADDITIONAL_CASES
}
PIPELINE_CASES = {"test_required_speech_pipeline"}
